//jshint esversion:6

const express = require( "express" );
const bodyParser = require( "body-parser" );
const ejs = require( "ejs" );
const _ = require( "lodash" );

const homeStartingContent = "Cultivation and the future are deeply interconnected. With the world's population expected to reach nearly 10 billion by 2050, sustainable and innovative approaches to agriculture will be essential to meet the growing demand for food. From vertical farming to regenerative practices, advancements in technology and environmental stewardship are paving the way for a brighter future in cultivation.";
const homecontent = " Here are a few topic ideas related to cultivation and the future:";
const teamMember = [
  {
    "name": "Naveen Kumar Pandit",
    "branch": "CSIT",
    "regdNo": "21020114",
    "profile": "https://media.licdn.com/dms/image/D4D03AQEuyxPLTInehQ/profile-displayphoto-shrink_400_400/0/1681502444738?e=1687392000&v=beta&t=ldojhgTMGez9ikC_ZhkRSq--L-FjxCGpLGAR9xwiIs8",
  },
  {
    "name": "Sooraj Kumar",
    "branch": "CSIT",
    "regdNo": "21020065",
    "profile": "https://media.licdn.com/dms/image/C5103AQE8wevI3zyXIg/profile-displayphoto-shrink_400_400/0/1568105969794?e=1687392000&v=beta&t=_thKVJ2V-cLU49kkBEDu5pJ2OSv0EDGrgr-uvfAeVHw"
  },
  {
    "name": "Gopal Krishna Jagadev",
    "branch": "CSIT",
    "regdNo": "21020115",
    "profile": "https://media.licdn.com/dms/image/D4D03AQFGRCmGxuaSeA/profile-displayphoto-shrink_400_400/0/1668454405883?e=1687392000&v=beta&t=EHHE6d58goEAy5q28fyOtNVRK2lYcjm8dI2xV9Vtln0"
  },
  {
    "name": "Vishal Singh",
    "branch": "CSIT",
    "regdNo": "21020067",
    "profile": "https://media.licdn.com/dms/image/D5603AQFpBGSAI552wQ/profile-displayphoto-shrink_400_400/0/1680418520697?e=1687392000&v=beta&t=-c-HLSkxOR4c92kbIdNPWU4ULUJHtuGIG14ZQcWKQwg"
  },
  {
    "name": "Sukhmati Mardi",
    "branch": "CSIT",
    "regdNo": "21020066",
    "profile": "https://media.licdn.com/dms/image/D4D03AQHtopbg2mLIvg/profile-displayphoto-shrink_400_400/0/1681707367926?e=1687392000&v=beta&t=tTHr3QfbbpQiFUpD47urMwrTH0KuXDw59J7aoKme1r4"
  },
  {
    "name": "Sambit Mohapatra",
    "branch": "CSIT",
    "regdNo": "21020063",
    "profile": "https://media.licdn.com/dms/image/D5603AQETFAektZZ60w/profile-displayphoto-shrink_400_400/0/1681709338174?e=1687392000&v=beta&t=03Fh4Kic_gzHn7_sarFU2uy9omLrbym9Q2sImVJS6-c"
  }
];

let app = express();

app.set( 'view engine', 'ejs' );

app.use( bodyParser.urlencoded( { extended: true } ) );
app.use( express.static( "public" ) );

const posts = [
  {
    "title": "Sustainable agriculture and the future of food production",
    "imgLink": "https://www.europarl.europa.eu/resources/library/images/20211012PHT14709/20211012PHT14709_original.jpeg",
    "content": "Sustainable agriculture is a farming system that aims to meet the needs of the present without compromising the ability of future generations to meet their own needs. It involves using practices that are environmentally friendly, economically viable, and socially responsible. Sustainable agriculture is becoming increasingly important as the global population grows and the demand for food increases. With climate change, soil degradation, and other environmental challenges, sustainable agriculture is crucial to ensure the long-term viability of our food system.",
    "body": {
      "point1": "Precision agriculture",
      "desc1": "Precision agriculture is a farming technique that uses technology to optimize crop yields while minimizing inputs such as fertilizer, water, and pesticides. By using sensors, drones, and other tools, farmers can collect data on soil moisture, nutrient levels, and other factors to make informed decisions about when and where to apply inputs. This approach can reduce waste, improve yields, and reduce the environmental impact of agriculture. Furthermore, precision agriculture has the potential to increase the efficiency of food production and help to feed a growing world population. Precision agriculture enables farmers to make data- driven decisions and tailor crop management to the specific needs of their fields.This technology can help to reduce the use of agrochemicals and water, lowering the environmental impact of agriculture.Additionally, precision agriculture can improve yields and reduce costs, which can increase the profitability of farming.The use of drones in agriculture is one example of precision agriculture.Drones equipped with sensors can collect data on crop health, nutrient levels, and soil moisture, which can be used to create detailed maps of the farm.This information can then be used to optimize inputs and improve crop yields. Another example of precision agriculture is the use of GPS- guided tractors.These tractors can precisely apply inputs such as fertilizer and pesticides only where they are needed, reducing waste and improving efficiency.Additionally, the use of precision irrigation systems can help to reduce water use and improve crop yields. While precision agriculture has the potential to improve the sustainability of agriculture, there are also potential drawbacks.The high cost of technology and the need for specialized skills and knowledge can be a barrier to adoption, especially for small - scale farmers.Additionally, the use of technology in agriculture can raise concerns about data privacy and ownership.",
      "point2": "Sustainable livestock management",
      "desc2": "Sustainable livestock management involves the use of techniques and practices that promote animal welfare, reduce the environmental impact of livestock production, and support the livelihoods of farmers. Livestock production is a significant contributor to greenhouse gas emissions, and unsustainable practices can lead to deforestation, soil degradation, and water pollution. Sustainable livestock management aims to reduce these negative impacts while maintaining the economic viability of farming. There are several approaches to sustainable livestock management, including improving animal welfare, reducing greenhouse gas emissions, and promoting biodiversity.For example, farmers can use rotational grazing to improve soil health and reduce erosion, plant trees to provide shade and shelter for livestock, and use manure as a fertilizer instead of chemical inputs.Additionally, reducing the amount of meat consumed in diets and promoting alternative protein sources such as plant- based proteins and lab- grown meat can help to reduce the environmental impact of livestock production. Improving animal welfare is an important aspect of sustainable livestock management.By providing livestock with adequate food, water, and shelter, as well as reducing stress and preventing disease, farmers can improve the health and well - being of their animals.This not only promotes ethical treatment of animals, but also improves the quality of meat and dairy products. Reducing greenhouse gas emissions from livestock production is another important aspect of sustainable livestock management.Livestock emit methane, a potent greenhouse gas, during digestion.Farmers can reduce these emissions by improving feed quality, using manure as a renewable energy source, and capturing and using methane as a fuel. Overall, sustainable livestock management practices can help to reduce the environmental impact of livestock production while supporting the economic viability of farming.By promoting animal welfare, reducing greenhouse gas emissions, and promoting biodiversity, sustainable livestock management can contribute to a more sustainable food system.",
      "point3": "Technology and innovation",
      "desc3": "Technology and innovation are critical components of sustainable agriculture. New technologies and techniques can help to increase efficiency, reduce waste, and minimize environmental impacts. For example, precision agriculture uses technology such as sensors, drones, and GPS to collect data and make precise decisions about planting, irrigation, and fertilizer application. This can reduce waste and increase yields while minimizing environmental impact. Similarly, genetic engineering and biotechnology can help to develop crops that are more resistant to pests and diseases, reducing the need for pesticides and herbicides. However, it is important to consider the potential risks and unintended consequences of new technologies in sustainable agriculture.For example, genetic engineering can have unintended impacts on ecosystems and biodiversity, and some precision agriculture technologies may contribute to overuse of inputs or loss of biodiversity.Therefore, it is important to carefully evaluate and regulate new technologies to ensure they are safe and sustainable.",
      "point4": "Conclusion",
      "desc4": "Sustainable agriculture is critical for the long-term viability of our food system. It involves using practices that are environmentally friendly, economically viable, and socially responsible. Soil health, biodiversity, agroforestry, and technology and innovation are all important aspects of sustainable agriculture. By promoting these practices, we can ensure the continued productivity and resilience of our agricultural systems while minimizing environmental damage and protecting future generations.",
    }
  },
  {
    "title": "The impact of technology on modern agriculture",
    "imgLink": "https://www.analyticsinsight.net/wp-content/uploads/2021/01/big-data-in-farming-1024x643.jpg",
    "content": "Modern agriculture has been transformed by the use of technology in recent years. From precision farming to automation and drones, new technologies are enabling farmers to produce food more efficiently, sustainably, and with greater precision. These advancements are helping to reduce waste, increase productivity, and improve the quality of food produced. This article will explore the impact of technology on modern agriculture, focusing on five key subtopics: precision farming, automation, drones, vertical farming, and blockchain. Each of these subtopics will be discussed in detail, highlighting the benefits and challenges associated with each technology. By the end of this article, readers will have a better understanding of how technology is changing the face of agriculture and how these advancements are helping to create a more sustainable and efficient food system.",
    "body": {
      "point1": "Precision Farming",
      "desc1": "Precision farming has emerged as a significant technological advancement in modern agriculture. This technique involves the use of sensors, GPS mapping, and other technologies to optimize crop yield and reduce waste. By using precision farming, farmers can collect real-time data on soil conditions, crop growth, and weather patterns, allowing them to adjust their practices accordingly. One of the key benefits of precision farming is that it reduces the use of fertilizers, pesticides, and herbicides, which can be harmful to the environment.By using sensors to monitor soil conditions, farmers can apply fertilizers and other inputs more precisely, reducing the amount of waste and runoff. Another benefit of precision farming is that it improves overall efficiency.By using GPS mapping to track the location of crops and equipment, farmers can optimize their planting and harvesting schedules, reducing downtime and increasing productivity.Additionally, by monitoring crop growth and health, farmers can identify potential issues before they become major problems, allowing them to take action to mitigate damage.",
      "point2": "Automation",
      "desc2": "Automation has transformed the way farmers work, enabling them to automate many of their tasks and increasing efficiency. Advances in robotics, artificial intelligence, and machine learning have enabled farmers to automate many of their tasks, including planting, harvesting, and irrigation. One of the most significant benefits of automation is that it reduces the need for manual labor.By using robots and other automated systems to perform tasks, farmers can reduce the amount of time and energy required to maintain their crops.This allows them to focus on higher- level tasks such as data analysis and decision- making. Another benefit of automation is that it reduces waste and improves efficiency.Automated systems can precisely apply fertilizers, pesticides, and other inputs, reducing waste and runoff.Additionally, by using GPS mapping and other technologies, farmers can optimize their planting and harvesting schedules, reducing downtime and increasing productivity.",
      "point3": "Technologies used on modern Farming",
      "desc3": "Modern agriculture has been revolutionized by technology, with a variety of tools and techniques being used to optimize farming operations and increase productivity. Precision farming, automation, biotechnology, weather monitoring, and digital marketing are just a few examples of the technologies that are being used in modern agriculture. Precision farming involves the use of advanced technologies such as GPS, sensors, and drones to collect data on crop yields, soil conditions, and other environmental factors.This data is then used to optimize crop production by applying fertilizers, water, and pesticides in precise amounts and at the right time.Automation, on the other hand, involves the use of robots and other machinery to carry out tasks such as planting, harvesting, and irrigation.This not only saves time and labor costs but also reduces the risk of human error. Biotechnology has also had a significant impact on modern agriculture.By using genetically modified crops that are resistant to pests and diseases, and can tolerate adverse environmental conditions, farmers can significantly increase their crop yields while reducing the use of pesticides and fertilizers. Weather monitoring and forecasting technologies have also transformed modern agriculture by enabling farmers to make informed decisions about when to plant, irrigate, and harvest their crops.Finally, e- commerce and digital marketing technologies have made it easier for farmers to sell their products directly to consumers, bypassing traditional intermediaries and increasing their profits. In conclusion, technology has had a profound impact on modern agriculture, leading to higher crop yields, more efficient farming practices, and greater profitability for farmers.As technology continues to evolve, we can expect even more significant improvements in the future, as farmers adopt new tools and techniques to optimize their operations.",
      "point4": "Conclusion",
      "desc4": "In conclusion, technology has had a profound impact on modern agriculture, revolutionizing the way farmers produce, distribute, and manage their crops. Precision farming has enabled farmers to optimize their use of resources and minimize waste, while automation has improved efficiency and reduced labor costs. Drones have opened up new opportunities for monitoring and managing crops, while vertical farming has allowed for greater productivity in urban areas. Finally, blockchain technology has the potential to increase transparency and traceability throughout the entire food supply chain. While these technologies offer many benefits, they also come with their own set of challenges.Some farmers may struggle with the cost of implementing new technologies, while others may have concerns around data privacy and security.Additionally, there may be questions around the long- term sustainability of certain practices, such as vertical farming. Despite these challenges, the overall impact of technology on modern agriculture has been overwhelmingly positive.By using technology to produce food more efficiently and sustainably, we can help ensure that there is enough food to feed the growing global population.As technology continues to advance, it is likely that we will see even more innovations in agriculture, paving the way for a more sustainable and efficient food system.",
    }
  },
  {
    "title": "The Role of Vertical Farming in Urban Areas",
    "imgLink": "https://www.prakati.in/wp-content/uploads/Vertical-Farming-in-India-concept-application-status-1.jpg",
    "content": "With the world's population projected to reach 9.7 billion by 2050, there is a growing need for sustainable food production. Vertical farming has emerged as a promising solution to the challenge of food production in urban areas. This article explores the role of vertical farming in urban areas, highlighting the benefits and challenges associated with this innovative farming practice. Vertical farming is an innovative and sustainable agricultural practice that involves growing crops in vertically stacked layers or racks, typically indoors or in controlled environments, such as high- rise buildings or warehouses in urban areas.This modern agricultural technique has gained significant attention in recent years due to its potential to address various challenges associated with traditional farming in urban areas, including limited land availability, climate change impacts, resource constraints, and food security concerns.",
    "body": {
      "point1": "Space-efficient",
      "desc1": "Vertical farming is an efficient use of space, making it ideal for urban areas with limited land availability. Vertical farms can be built in high-rise buildings or in repurposed warehouses, allowing for year-round food production in densely populated areas. Having vertical farms in the midst of cities could also help to make us more aware of how our food is produced, says Falagan.Pasona Urban Farm, for example, wasn't just for show – it allowed office workers to harvest their own food at work, which the company hoped would improve both their mental and physical health. Falagan says that having a closer connection with where our food comes from might encourage consumers to be more careful with food waste, too. Most vertical farms currently concentrate on low- biomass crops – things like herbs, salads and small fruits and vegetables which weigh less per portion – because there is a greater yield for the amount of heat, light and water that needs to be supplied.They also have short life cycles, so make maximum use of space, says Vickers.A leafy green will grow quickly and be ready to harvest in days or weeks, whereas a pumpkin would take months to grow and needs to cure in sunlight.",
      "point2": "Controlled environment",
      "desc2": "A controlled environment refers to a setting or condition where certain variables are regulated or manipulated to maintain a specific level of control over the environment. This can be achieved through various means, such as physical barriers, technological systems, or protocols to manage and manipulate the conditions within the environment. Controlled environments are commonly used in scientific research, manufacturing, agriculture, and other industries where precise conditions are required for optimal results. Examples of controlled environments include: Laboratories: Scientific research often requires controlled environments to conduct experiments and collect data.Laboratories may have controlled temperature, humidity, lighting, and airflow to ensure consistent conditions for experiments and accurate results. Cleanrooms: Cleanrooms are controlled environments used in industries such as electronics manufacturing, pharmaceuticals, and aerospace, where airborne particles, temperature, and humidity need to be strictly regulated to prevent contamination. Greenhouses: In agriculture, greenhouses provide a controlled environment for growing plants by regulating factors such as temperature, humidity, light, and ventilation to optimize plant growth and yield.",
      "point3": "Sustainable farming",
      "desc3": "Vertical farming is a sustainable form of farming that uses significantly less water, pesticides, and fertilizer than traditional farming. The use of hydroponic and aeroponic systems also eliminates the need for soil, reducing the risk of soil-borne diseases and pests. A farm that can 'produce perpetually', yet has negative effects on environmental quality elsewhere is not sustainable agriculture.An example of a case in which a global view may be warranted is the application of fertilizer or manure, which can improve the productivity of a farm but can pollute nearby rivers and coastal waters ( eutrophication ).[ 23 ] The other extreme can also be undesirable, as the problem of low crop yields due to exhaustion of nutrients in the soil has been related to rainforest destruction.[ 24 ] In Asia, the specific amount of land needed for sustainable farming is about 12.5 acres which include land for animal fodder, cereal production as a cash crop, and other food crops.The most important factors for a farming site are climate, soil, nutrients and water resources.Of the four, water and soil conservation are the most amenable to human intervention.When farmers grow and harvest crops, they remove some nutrients from the soil.Without replenishment, the land suffers from nutrient depletion and becomes either unusable or suffers from reduced yields.Sustainable agriculture depends on replenishing the soil while minimizing the use or need of non- renewable resources, such as natural gas or mineral ores",
      "point4": "Conclusion",
      "desc4": "Vertical farming has the potential to revolutionize food production in urban areas, providing a sustainable and efficient solution to the challenge of food production in densely populated areas. The use of vertical farming technology can increase yields, reduce water usage, and provide access to fresh produce in areas with limited access to fresh produce. However, the high cost of technology adoption and energy consumption remains a challenge for widespread adoption of vertical farming. Nevertheless, as technology advances and costs decrease, vertical farming will likely become an increasingly important component of sustainable urban agriculture.",
    }
  },
  {
    "title": "Climate Change and its Effects on Agriculture",
    "imgLink": "https://pureecoindia.in/wp-content/uploads/2021/07/Dry-soil-and-green-landscape-juxtaposition-Pure-Eco-India.jpg",
    "content": "Climate change has become a major concern globally, affecting various aspects of life, including agriculture. The agriculture sector is particularly vulnerable to climate change, as farming practices are highly dependent on weather patterns. This article explores the effects of climate change on agriculture, highlighting the challenges faced by farmers and potential solutions to mitigate its effects. Changes in the frequency and severity of droughts and floods could pose challenges for farmers and ranchers and threaten food safety.   Meanwhile, warmer water temperatures are likely to cause the habitat ranges of many fish and shellfish species to shift, which could disrupt ecosystems.Overall, climate change could make it more difficult to grow crops, raise animals, and catch fish in the same ways and same places as we have done in the past.The effects of climate change also need to be considered along with other evolving factors that affect agricultural production, such as changes in farming practices and technology.",
    "body": {
      "point1": "Changes in weather patterns",
      "desc1": "Climate change has led to changes in weather patterns, including extreme weather events such as droughts, floods, and heatwaves. These weather events have a significant impact on crop yields, soil quality, and water availability, leading to food insecurity and economic losses. Agriculture and fisheries are highly dependent on the climate. Increases in temperature and carbon dioxide (CO2) can increase some crop yields in some places. But to realize these benefits, nutrient levels, soil moisture, water availability, and other conditions must also be met. Changes in the frequency and severity of droughts and floods could pose challenges for farmers and ranchers and threaten food safety.   Meanwhile, warmer water temperatures are likely to cause the habitat ranges of many fish and shellfish species to shift, which could disrupt ecosystems. Overall, climate change could make it more difficult to grow crops, raise animals, and catch fish in the same ways and same places as we have done in the past. The effects of climate change also need to be considered along with other evolving factors that affect agricultural production, such as changes in farming practices and technology.",
      "point2": "Pests and diseases",
      "desc2": "Climate change has led to the emergence of new pests and diseases, and the spread of existing ones, affecting crop yields and quality. This has increased the use of pesticides, leading to environmental degradation and health risks. The damage to plants caused by competition from weeds and by other pests including viruses, bacteria, fungi, and insects greatly impairs their productivity and in some instances can totally destroy a crop. Today, dependable crop yields are obtained by using disease-resistant varieties, biological control practices, and by applying pesticides to control plant diseases, insects, weeds, and other pests. In 1983, $1.3 billion was spent on pesticides—excluding herbicides—to protect and limit the damage to crops from plant diseases, nematodes, and insects. The potential crop losses in the absence of pesticide use greatly exceeds that value. For about 100 years, breeding for disease resistance has been an important component of agricultural productivity worldwide.But the successes achieved by plant breeding are largely empirical and can be ephemeral.That is, because of a lack of basic information about the function of genes for resistance, studies are often random rather than specifically targeted explorations.In addition, any results can be short- lived because of the changing nature of pathogens and other pests as new genetic information is introduced into complex agroecological systems",
      "point3": "Soil degradation",
      "desc3": "Climate change has led to soil degradation, reducing soil fertility and productivity. Extreme weather events, such as floods and droughts, cause erosion and nutrient loss, leading to reduced yields and increased land degradation. Soil degradation is the decline in soil condition caused by its improper use or poor management, usually for agricultural, industrial or urban purposes.It is a serious environmental problem.Soils are a fundamental natural resource, and are the basis for all terrestrial life.Avoiding soil degradation is crucial to our well- being.Soil degradation is the physical, chemical and biological decline in soil quality.It can be the loss of organic matter, decline in soil fertility, and structural condition, erosion, adverse changes in salinity, acidity or alkalinity, and the effects of toxic chemicals, pollutants or excessive flooding.",
      "point4": "Conclusion",
      "desc4": "Climate change is a significant challenge facing agriculture, threatening food security and livelihoods globally. The effects of climate change on agriculture are diverse, affecting weather patterns, soil quality, and crop yields. However, with the adoption of climate-smart agriculture practices, such as crop diversification, improved water management, and soil conservation practices, farmers can adapt to the effects of climate change and mitigate its impact on agriculture. It is crucial that governments, international organizations, and the private sector work together to support farmers in adopting climate-smart agriculture practices, ensuring food security and sustainable agriculture in the face of climate change.",
    }
  },
  {
    "title": "The Potential of Regenerative Farming to Combat Environmental Degradation",
    "imgLink": "https://www.bentoli.com/wp-content/uploads/2017/07/CommercialFarming-1.jpg",
    "content": "Regenerative farming has emerged as a promising solution to combat environmental degradation and promote sustainable agriculture. Regenerative farming is a holistic approach that emphasizes soil health, biodiversity, and ecosystem services. This article explores the potential of regenerative farming to combat environmental degradation and promote sustainable agriculture. Regenerative agriculture improves soil health, primarily through the practices that increase soil organic matter.This not only aids in increasing soil biota diversity and health, but increases biodiversity both above and below the soil surface, while increasing both water holding capacity and sequestering carbon at greater depths, thus drawing down climate- damaging levels of atmospheric CO2, and improving soil structure to reverse civilization - threatening human - caused soil loss.Research continues to reveal the damaging effects to the soil from tillage, applications of agricultural chemicals and salt - based fertilizers, and carbon mining.Regenerative Agriculture reverses this paradigm to build for the future.",
    "body": {
      "point1": "Soil health",
      "desc1": "Soil health in Regenerative farming focuses on building soil health, using techniques such as cover cropping, crop rotation, and reduced tillage. This enhances soil biodiversity, improves soil structure, and reduces erosion and nutrient loss, leading to increased yields and improved resilience to climate change.Soil health is the condition of the soil in a defined space and at a defined scale relative to a set of benchmarks that encompass healthy functioning. It would not be appropriate to refer to soil health for soil-roadbed preparation, as in the analogy of soil quality in a functional class. The definition of soil health may vary between users of the term as alternative users may place differing priorities upon the multiple functions of a soil. Therefore, the term soil health can only be understood within the context of the user of the term, and their aspirations of a soil, as well as by the boundary definition of the soil at issue. Finally, intrinsic to the discussion on soil health are many potentially conflicting interpretations, especially ecological landscape assessment vs agronomic objectives, each claiming to have soil health criteria.",
      "point2": "Biodiversity",
      "desc2": "Biodiversity in Regenerative farming promotes biodiversity by planting a variety of crops, encouraging natural habitats for beneficial insects, and avoiding the use of pesticides and herbicides. This promotes ecosystem services, such as pollination and pest control, and enhances resilience to environmental stressors. Biodiversity and regenerative farming are two concepts that are closely related and have gained increasing attention in recent years due to their potential to address environmental challenges such as climate change, soil degradation, and loss of biodiversity. Biodiversity refers to the variety of life on Earth, including the diversity of plant and animal species, genetic diversity within species, and the diversity of ecosystems. Regenerative farming is an approach to agriculture that seeks to restore and enhance the health and resilience of agricultural ecosystems, including soil, water, plants, and animals, through ecological principles and practices that mimic natural processes. Biodiversity is essential for the functioning and sustainability of ecosystems, including agricultural ecosystems.It provides a range of ecosystem services such as pollination, pest control, nutrient cycling, and soil fertility, which are crucial for agricultural productivity.Biodiversity in and around farms can help maintain ecosystem balance, reduce the need for chemical inputs, and increase the resilience of farming systems to pests, diseases, and climate change impacts. desc2",
      "point3": "Carbon sequestration ",
      "desc3": "Carbon sequestration in Regenerative farming practices can sequester carbon in the soil, reducing greenhouse gas emissions and mitigating the effects of climate change. Practices such as cover cropping, crop rotation, and reduced tillage can increase soil organic matter and carbon content, enhancing the ability of soil to sequester carbon. Carbon sequestration is the process of capturing and storing carbon dioxide (CO2) from the atmosphere in plants, soils, and other organic matter, helping to mitigate climate change by reducing the concentration of greenhouse gases in the atmosphere. Regenerative farming practices can play a significant role in carbon sequestration by enhancing the capacity of agricultural ecosystems to capture and store carbon.",
      "point4": "Conclusion",
      "desc4": "Regenerative farming has the potential to combat environmental degradation and promote sustainable agriculture, through practices that improve soil health, promote biodiversity, sequester carbon, and provide economic benefits to farmers and communities. As the effects of climate change and environmental degradation continue to threaten agriculture and food security, regenerative farming provides a promising solution for sustainable agriculture. It is crucial that governments, international organizations, and the private sector support and promote regenerative farming practices, ensuring a sustainable future for agriculture and the environment.",
    }
  },
  {
    "title": "The Future of Genetic Modification and Crop Breeding",
    "imgLink": "https://thumbs.dreamstime.com/b/lab-assistant-holding-beaker-plant-blurred-background-closeup-biological-chemistry-lab-assistant-holding-beaker-plant-140614074.jpg",
    "content": "Genetic modification and crop breeding have been an important aspect of agriculture for many years. Genetic modification involves altering the DNA of a plant to improve its characteristics, such as resistance to pests and diseases, while crop breeding involves selectively breeding plants to create new varieties with desirable traits. With advancements in technology and increasing demands for food, the future of genetic modification and crop breeding is rapidly changing. In this article, we will explore five subtopics related to the future of genetic modification and crop breeding.",
    "body": {
      "point1": "Precision breeding and gene editing",
      "desc1": "Precision breeding and gene editing technologies are rapidly advancing and hold significant promise for the future of agriculture. These technologies are precise, fast, and enable scientists to target specific genes in the plant's DNA. One of the significant benefits of precision breeding and gene editing is the ability to create crops that are more resistant to pests and diseases. For example, scientists can modify a plant's DNA to produce toxins that repel pests, reducing the need for harmful pesticides. Another advantage of these technologies is the ability to create crops with longer shelf lives.By altering genes responsible for spoilage, scientists can develop crops that stay fresh for more extended periods, reducing food waste.Additionally, precision breeding and gene editing can be used to develop crops that require less water and fertilizer, making agriculture more sustainable. There are still challenges facing these technologies.For example, it can be challenging to ensure that only the desired genes are targeted and modified, and ethical concerns about the impact of genetic modification on the environment remain.Nevertheless, precision breeding and gene editing hold enormous potential for creating crops that are better suited to meet the world's growing food needs.",
      "point2": "Sustainable agriculture",
      "desc2": "Sustainable agriculture is essential for meeting the needs of a growing population while preserving the environment. Genetic modification and crop breeding can play an essential role in creating more sustainable agriculture. By developing crops that require less water and fertilizer, less land can be used for agriculture, reducing the strain on natural resources. Additionally, genetically modified and selectively bred crops can be designed to be more resistant to pests and diseases.This reduces the need for pesticides, which can harm the environment and human health.Furthermore, crops that require fewer resources can reduce greenhouse gas emissions associated with agriculture. The creation of more sustainable agriculture is crucial for the long- term survival of the planet.Genetic modification and crop breeding can help achieve this goal by creating crops that are better suited to withstand environmental pressures and require fewer resources.",
      "point3": "Crop diversity and resilience",
      "desc3": "The diversity of crops is crucial for ensuring global food security and resilience in the face of environmental challenges. Genetic modification and crop breeding can help to increase crop diversity by developing new varieties of crops with unique traits. For example, scientists can modify the genes of crops to increase their tolerance to extreme temperatures, drought, or flooding.This can help to ensure that crops can survive and thrive in changing environmental conditions. Additionally, genetic modification and crop breeding can be used to create crops that are more nutritious.By altering the genes responsible for producing essential vitamins and minerals, scientists can develop crops that provide greater nutritional value. The creation of more diverse and resilient crops is essential for ensuring global food security in the face of a changing climate and growing population.Genetic modification and crop breeding offer powerful tools to achieve this goal.",
      "point4": "Conclusion",
      "desc4": "In conclusion, the future of genetic modification and crop breeding holds great promise for improving agriculture and food production. Advances in technology have enabled scientists to develop more precise and efficient tools for genetic engineering and gene editing, allowing for the creation of crops with desirable traits such as increased yield, pest resistance, and drought tolerance. While concerns over safety and ethics remain, it is clear that genetic modification and crop breeding will play an important role in addressing global challenges such as food insecurity, climate change, and population growth. As research and development continue in this field, it is important to balance innovation with responsible and transparent regulation to ensure the safe and equitable use of these technologies.",
    }
  },
  {
    "title": "How Automation and Robotics are Changing the Agricultural Industry",
    "imgLink": "https://www.bearingtips.com/wp-content/uploads/2021/06/SMB320-Agricultural-drone.jpg",
    "content": "The agricultural industry has undergone significant changes over the years, and technological advancements have played a significant role in these changes. The use of automation and robotics is one such technological innovation that has revolutionized the agricultural industry. With the use of these technologies, farming has become more efficient, sustainable, and cost-effective. In this article, we will explore how automation and robotics are changing the agricultural industry.",
    "body": {
      "point1": "Precision Farming",
      "desc1": "Precision farming is a technique that utilizes technology to optimize crop yields and reduce waste. With the help of sensors, drones, and GPS, farmers can analyze their fields to determine the exact amounts of water, fertilizer, and pesticides needed for each crop. This reduces the overall amount of resources required and minimizes the impact on the environment. Moreover, precision farming also enables farmers to detect issues such as pests, disease, or nutrient deficiencies in real-time, allowing them to take corrective actions quickly. For example, a drone with a multispectral camera can capture images of crops and provide data on crop health, moisture levels, and nutrient levels.This data is then analyzed to determine the exact amount of inputs required for optimal growth.Farmers can also use sensors in the soil to monitor moisture levels and nutrient content, which helps them make informed decisions on irrigation and fertilization.",
      "point2": "Automated Harvesting",
      "desc2": "The harvesting of crops has traditionally been a labor-intensive process, requiring a large workforce to manually pick and pack crops. With the advent of automated harvesting systems, this is changing. Harvesting robots can now perform the task of picking, sorting, and packing crops with high accuracy and speed. This not only reduces labor costs but also increases productivity and reduces wastage. Furthermore, automated harvesting systems also help reduce the physical strain on farm workers, which can result in fewer injuries and health problems. For example, a strawberry- picking robot developed by Japanese firm, Shibuya Seiki, uses a combination of 3D imaging and artificial intelligence to identify ripe strawberries and pick them with high accuracy.Similarly, a lettuce- harvesting robot developed by California - based Blue River Technology, uses computer vision and machine learning to identify and harvest lettuce heads at high speed.",
      "point3": "Autonomous Tractors",
      "desc3": "Tractors are an essential tool for farmers, used for plowing, planting, and harvesting. With the introduction of autonomous tractors, farmers can now perform these tasks without the need for human intervention. These tractors use GPS and sensors to navigate through fields and perform their tasks with precision. This reduces labor costs and increases efficiency, allowing farmers to cover more ground in less time. Moreover, autonomous tractors also reduce the risk of accidents and injuries caused by human error. For example, John Deere's autonomous tractor, the AutoTrac, uses GPS and sensors to perform tasks such as planting, tillage, and spraying. The tractor can be programmed to perform tasks autonomously, allowing farmers to focus on other aspects of their farm operation.",
      "point4": "Conclusion",
      "desc4": "Automation and robotics are transforming the agricultural industry, making it more efficient, sustainable, and profitable. Precision farming, automated harvesting, autonomous tractors, crop monitoring, and livestock management are just a few examples of how these technologies are changing the way we farm. As technology continues to advance, we can expect to see even more innovation in the agricultural industry, with new and exciting possibilities for farmers and consumers alike. While there may be challenges to adopting these new technologies, the benefits they offer are significant, and they have the potential to revolutionize the way we produce and consume food.",
    }
  },
  {
    "title": "Hydroponics and its potential to feed the world's growing population",
    "imgLink": "https://console.kr-asia.com/wp-content/uploads/2020/12/Barton-Breeze-Farm-1-scaled.jpg",
    "content": "Hydroponics is a soilless way of growing plants, which uses a nutrient-rich solution to provide the plants with all the necessary nutrients for growth. The technique has gained popularity in recent years due to its potential to produce high yields of crops in a limited space, with minimal water usage, and without the need for soil or traditional farming practices. Hydroponics is increasingly being seen as a promising solution to feed the world's growing population, which is expected to reach 9.7 billion by 2050. In this article, we will explore the potential of hydroponics in feeding the world and its advantages over traditional farming practices.",
    "body": {
      "point1": "Efficient use of space",
      "desc1": "Hydroponics is an ideal solution for maximizing the use of available space. Hydroponic systems can be designed to fit any space, from a small balcony or backyard to a large commercial farm. Hydroponic systems can be set up vertically, which means more plants can be grown per square meter of space. For example, a hydroponic system can grow 10 times more plants per square meter than traditional farming methods. Vertical hydroponic systems utilize space efficiently by stacking multiple layers of plants.This system saves a lot of space, making it ideal for urban agriculture.The system is simple and easy to maintain, and it is highly productive, making it a popular choice for commercial farming.The vertical hydroponic system is highly effective at growing crops such as lettuce, herbs, and strawberries. In addition to saving space, hydroponics also reduces the need for land to grow crops.This is especially important in areas where arable land is limited or where land is needed for other purposes.",
      "point2": "Reduced water usage",
      "desc2": "Water scarcity is a growing concern globally, and traditional farming practices consume vast amounts of water. Hydroponics, on the other hand, uses only a fraction of the water needed in traditional farming. The water used in hydroponics is recycled and reused, reducing water usage by up to 90% compared to traditional farming. Hydroponic systems use a nutrient- rich solution to grow plants instead of soil.The solution is circulated through the system, providing the plants with the necessary nutrients.As the plants absorb the nutrients, the excess solution is collected and reused.This system significantly reduces water usage compared to traditional farming practices, where water is often wasted through runoff or evaporation. Hydroponic systems are also designed to minimize water loss through evaporation.The systems are enclosed, and the nutrient solution is circulated through pipes, preventing water from evaporating into the atmosphere.",
      "point3": "No need for soil",
      "desc3": "Hydroponics eliminates the need for soil, which is a significant advantage over traditional farming. Soil-borne diseases and pests are a significant threat to crops in traditional farming, requiring the use of pesticides and other chemicals. In hydroponics, plants are grown in a nutrient-rich solution, which eliminates the need for pesticides and chemicals. The absence of soil also reduces the risk of erosion and soil degradation. In hydroponics, plants are grown using a variety of growing mediums, such as coconut coir, peat moss, or perlite.These materials provide support for the plants and retain moisture while allowing the nutrient solution to circulate freely.Hydroponic systems can be set up indoors or outdoors, making them ideal for urban agriculture or areas with poor soil quality. Hydroponics can also be used to grow a wide variety of plants, including fruits, vegetables, herbs, and flowers.This versatility makes hydroponics a popular choice for commercial farming.",
      "point4": "Conclusion",
      "desc4": "Hydroponics is a promising solution to feed the world's growing population, and its potential benefits are numerous. Hydroponics can be used to maximize space, reduce water usage, eliminate the need for soil, increase yields, and provide greater food security. As the world's population continues to grow, hydroponics can provide a reliable and sustainable source of fresh produce, helping to address food insecurity and improve access to healthy food. With ongoing advancements in technology and growing practices, hydroponics is poised to play an increasingly important role in feeding the world's population in the years to come.",
    }
  },
  {
    "title": "Organic farming and the benefits of locally grown food",
    "imgLink": "https://www.colorado.edu/ecenter/sites/default/files/styles/large/public/callout/image1.png?itok=hsYKMfzq",
    "content": "Organic farming and locally grown food are becoming increasingly popular as people become more aware of the benefits they offer. Organic farming refers to a method of farming that avoids the use of synthetic fertilizers, pesticides, and genetically modified organisms, and instead relies on natural processes and biodiversity to grow crops. Locally grown food, on the other hand, refers to food that is grown and sold within the local community, reducing the carbon footprint associated with transportation and supporting local farmers. In this article, we will explore the benefits of organic farming and locally grown food in more detail.",
    "body": {
      "point1": "Health Benefits",
      "desc1": "One of the most significant benefits of organic farming and locally grown food is the health benefits they offer. Organic produce is often higher in nutrients than conventionally grown produce, as organic farming methods help to maintain soil health and biodiversity, resulting in healthier plants. For example, a study published in the Journal of Agricultural and Food Chemistry found that organic tomatoes had higher levels of vitamin C and antioxidants than conventionally grown tomatoes. Additionally, organic farming avoids the use of synthetic chemicals that can harm human health, such as pesticides, herbicides, and fungicides.By consuming organic food, individuals can reduce their exposure to these harmful chemicals and lower their risk of chronic diseases such as cancer, allergies, and neurological damage.Moreover, organic farming encourages the use of sustainable farming practices like crop rotation, cover cropping, and natural pest management that increase soil fertility, reduce erosion, and promote the growth of healthy plants.By consuming locally grown organic food, individuals can ensure that they are getting the most nutritious, safe, and environmentally friendly food available.",
      "point2": "Environmental Benefits",
      "desc2": "Organic farming has numerous environmental benefits. One of the most significant benefits is the reduction of pollution associated with conventional farming. Synthetic chemicals used in conventional farming practices can contaminate waterways and harm wildlife, leading to ecosystem disruption. Additionally, organic farming methods rely on natural processes such as crop rotation, composting, and natural pest control, which help to reduce the use of synthetic chemicals. Organic farming also helps to preserve soil health, as the use of synthetic fertilizers can damage soil microbiota.By maintaining soil health, organic farming practices help to sequester carbon in the soil, reducing greenhouse gas emissions.Furthermore, organic farming supports biodiversity by providing habitat for wildlife, including birds, insects, and small mammals.By supporting organic farming and consuming locally grown food, individuals can contribute to the preservation of the environment and the promotion of sustainable agriculture.",
      "point3": "Community Benefits:",
      "desc3": "Local food systems foster a sense of community by connecting people to the land and the people who grow their food. When individuals purchase food directly from local farmers, they can learn about the farming practices used, the challenges faced, and the unique qualities of the food being grown. This helps to build a sense of trust and connection between consumers and farmers, fostering a more resilient and supportive community. Moreover, local food systems provide opportunities for farmers to share knowledge and skills, collaborate on new projects, and support each other through difficult times.By supporting local farmers, consumers are also supporting the development of a robust and diverse local food system that benefits everyone in the community.Additionally, local food systems can help to increase food security, as they provide a reliable source of fresh, nutritious food even during times of crisis or supply chain disruptions.",
      "point4": "Conclusion",
      "desc4": "desc3Organic farming and locally grown food offer numerous benefits for individuals, communities, and the environment. By choosing to support organic farming practices and purchasing locally grown food, individuals can enjoy high-quality, nutritious, and delicious food while supporting sustainable agriculture and local economies. Moreover, by reducing the carbon footprint associated with transportation and supporting the preservation of biodiversity and soil health, individuals can contribute to the development of a more sustainable and resilient food system. Overall, organic farming and locally grown food are an excellent choice for anyone looking to make a positive impact on their health, the environment, and their community.",
    }
  },
  {
    "title": "The Intersection of Agriculture and Renewable Energy",
    "imgLink": "https://pulitzercenter.org/sites/default/files/styles/orig_optimized/public/inline-images/DSC_0025.JPG.webp?itok=oecqAK0O",
    "content": "The world's population is expected to reach 9.7 billion by 2050, which will lead to an increase in demand for food and energy. In this context, agriculture and renewable energy are becoming more intertwined, as the former can provide opportunities for the latter to develop and grow sustainably. The intersection of agriculture and renewable energy offers multiple benefits, including reduced greenhouse gas emissions, increased efficiency, and more resilient food systems.",
    "body": {
      "point1": "Solar Energy in Agriculture",
      "desc1": "Solar energy is one of the most promising renewable energy sources for agriculture. Solar panels can be installed on farms to generate electricity, which can be used to power agricultural processes, such as irrigation, lighting, and ventilation. Solar energy can also be used to charge batteries, which can power equipment such as tractors and other farm machinery. This reduces the need for fossil fuels, which are expensive and produce greenhouse gases. In addition, solar- powered pumps can be used to draw water from wells or rivers, which is particularly important in regions where water is scarce or unreliable.Solar - powered drip irrigation systems can also be used to irrigate crops, which can significantly reduce water usage and increase crop yields. Moreover, solar energy can help farmers reduce their energy bills, which can be a significant expense in agriculture.According to the US Department of Agriculture, the use of solar panels on farms can reduce energy bills by up to 90%.This can help farmers save money and reinvest in their operations.",
      "point2": "Wind Energy and Crop Production",
      "desc2": "Wind energy is another promising renewable energy source for agriculture. Wind turbines can be installed on farmland to generate electricity from wind power. This energy can be used to power farm operations, or sold to the grid. Wind energy is a clean and renewable source of energy that can help reduce greenhouse gas emissions and reliance on fossil fuels. Wind turbines can also be designed to have a minimal impact on crop production.Careful placement and design of wind turbines can help minimize their impact on crops, and in some cases, even improve crop yields.For example, wind turbines can create a microclimate that reduces temperature extremes and improves air circulation, which can benefit certain crops. Moreover, wind energy can provide a new source of income for farmers.By selling excess energy to the grid, farmers can diversify their income streams and reduce their dependence on traditional agricultural practices.",
      "point3": "Biogas from Agricultural Waste",
      "desc3": "Biogas is another renewable energy source that can be produced from agricultural waste. Biogas is produced when organic matter, such as agricultural waste, is decomposed in the absence of oxygen. This gas can be used as a renewable energy source to generate electricity, heat, or fuel for transportation. Farmers can use biogas from agricultural waste to power their farm operations, reducing their reliance on fossil fuels.Biogas production can also help reduce greenhouse gas emissions, as it reduces the amount of methane released into the atmosphere during the decomposition process.",
      "point4": "Conclusion",
      "desc4": "In conclusion, the intersection of agriculture and renewable energy presents a significant opportunity for creating a more sustainable and resilient food system. The adoption of renewable energy technologies in agriculture can help reduce carbon emissions, increase efficiency, and create more sustainable practices. With the growing demand for food and energy, it is crucial to explore new and innovative ways to integrate renewable energy into agriculture for a more sustainable future. As the world continues to face the challenges of climate change and food insecurity, the integration of renewable energy in agriculture offers a potential solution.It is essential for policymakers, farmers, and stakeholders in the agriculture industry to recognize the benefits of renewable energy and support the transition towards more sustainable practices.By doing so, we can ensure that future generations have access to healthy and nutritious food while minimizing our impact on the environment.",
    }
  }
];

app.get( "/", function ( req, res )
{
  res.render( "home", {
    startingContent: homeStartingContent,
    content: homecontent,
    posts: posts,
  } );
} );

app.get( "/about", function ( req, res )
{
  res.render( "about", {
    team: teamMember
  } );
} );

app.get( "/feedback", function ( req, res )
{
  res.render( "feedback" );
} );

app.get( "/compose", function ( req, res )
{
  res.render( "compose" );
} );

app.post( "/compose", function ( req, res )
{
  const post = {
    title: req.body.postTitle,
    imgLink: req.body.imgLink,
    content: req.body.postBody,
    body: {
      point1: req.body.p1,
      desc1: req.body.d1,
      point2: req.body.p2,
      desc2: req.body.d2,
      point3: req.body.p3,
      desc3: req.body.d3,
      point4: req.body.p4,
      desc4: req.body.d4
    }

  };
  console.log( post );

  posts.push( post );

  res.redirect( "/" );
} );

app.get( "/posts/:postName", function ( req, res )
{
  const reqTitle = _.lowerCase( req.params.postName );

  posts.forEach( function ( post )
  {
    const storedTitle = _.lowerCase( post.title );

    if ( storedTitle === reqTitle )
    {
      res.render( "post", {
        title: post.title,
        img: post.imgLink,
        content: post.content,
        title1: post.body.point1,
        desc1: post.body.desc1,
        title2: post.body.point2,
        desc2: post.body.desc2,
        title3: post.body.point3,
        desc3: post.body.desc3,
        title4: post.body.point4,
        desc4: post.body.desc4
      } );
    }
  } );
} );

app.listen( 3000, function ()
{
  console.log( "Server started on port 3000" );
} );
